version: 0.0
os: linux
files:
  - source: /
    destination: /tmp
hooks:
  ApplicationStop:
    - location: scripts/stop_jar.sh
      timeout: 20
      runas: root
  ApplicationStart:
    - location: scripts/start_jar.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/health_check.sh
      timeout: 30