version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "installing java 17"
  pre_build:
    commands:
      - echo "we are in the pre build phase"
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/FirstEC2.jar
    - appspec.yml
  discard-paths: yes