version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Java 17"
  pre_build:
    commands:
      - echo "Pre-build"
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - ./target/billing-service.jar
    - ./scripts/*.sh
    - ./.aws/amazon-cloudwatch-agent.json
    - appspec.yml
  discard-paths: yes