AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  SecurityGroupDescription:
    Description: Security Group Description
    Type: String

  EC2Name:
    Description: EC2 Name
    Type: String

  GitHubConnectionARN:
    Description: ARN of the github connection to your repo
    Type: String

    # *** The remaining parameters should either be:
    # - overridden via changing "Default" here (PREFERABLE, since then they're in source control)
    # - or you can pass them in when creating / updating the stack

    # *** The owner of the Github repo for this application.
  GitHubOwner:
    Type: String
    Default: AliakseiKotsikau
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubRepo:
    Type: String
    Default: awscourse
    AllowedPattern: "[A-Za-z0-9-]+"

  GitHubBranch:
    Type: String
    Default: master
    AllowedPattern: "[A-Za-z0-9-]+"

  ArtifactStoreArn:
    Description: ARN of the S3 artifactory store
    Type: String
    Default: "arn:aws:s3:::codepipeline-eu-north-1-674117139"

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: eu-north-1a
      ImageId: ami-077c0b6b39b5dcbee
      InstanceType: t3.micro
      SecurityGroups:
        - !Ref EC2SecurityGroupForTraffic
      Tags:
        - Key: Name
          Value: !Ref EC2Name

  # our second EC2 security group
  EC2SecurityGroupForTraffic:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Ref SecurityGroupDescription
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
# ---------------------------------------------------------------------------
  AppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn:
        Ref: "arn:aws:iam::166601305423:role/service-role/AWSCodePipelineServiceRole-eu-north-1-MainPipeline"
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHubV2
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                ConnectionArn: !Ref GitHubConnectionARN
              RunOrder: 1
#        -
#          Name: Beta
#          Actions:
#            -
#              Name: BetaAction
#              InputArtifacts:
#                -
#                  Name: SourceOutput
#              ActionTypeId:
#                Category: Deploy
#                Owner: AWS
#                Version: 1
#                Provider: CodeDeploy
#              Configuration:
#                ApplicationName:
#                  Ref: ApplicationName
#                DeploymentGroupName:
#                  Ref: DeploymentGroupName
#              RunOrder: 1
#        -
#          Name: Release
#          Actions:
#            -
#              Name: ReleaseAction
#              InputArtifacts:
#                -
#                  Name: SourceOutput
#              ActionTypeId:
#                Category: Deploy
#                Owner: AWS
#                Version: 1
#                Provider: CodeDeploy
#              Configuration:
#                ApplicationName:
#                  Ref: ApplicationName
#                DeploymentGroupName:
#                  Ref: DeploymentGroupName
#              RunOrder: 1
      ArtifactStore:
        Type: S3
        Location:
          Ref: "arn:aws:s3:::codepipeline-eu-north-1-674117139"
#        EncryptionKey:
#          Id: arn:aws:kms:useast-1:ACCOUNT-ID:key/KEY-ID
#          Type: KMS

  Resources:
    MyS3Bucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: 'your-existing-bucket-name'

  Outputs:
    S3BucketArn:
      Description: 'S3 Bucket ARN'
      Value: !Sub 'arn:aws:s3:::${MyS3Bucket}'



