AWSTemplateFormatVersion: 2010-09-09 # This version is a current default value for CloudFormation
Description: "CloudPipeline implementation based on GitHub connection and EC2 deployment (https://jennapederson.com/blog/2021/11/26/using-cloudformation-to-automate-build-test-deploy-with-codepipeline-part-3/)"

Parameters:
  EnvironmentType:
    Description: Choose which environment should be used
    Type: String
    AllowedValues:
      - dev
      - test
    Default: dev
  AvailabilityZone:
    Description: Choose AZ, which should be used for EC2 creation
    Type: AWS::EC2::AvailabilityZone::Name
    Default: eu-north-1a
  TagNameValue:
    Description: Enter application names separated by commas (order, billing, ...)
    Type: String
    Default: order, billing
  CodeArtifactCentralStore:
    Description: Enter CodeArtifact external connection
    Type: String
    AllowedValues:
      - public:maven-central
      - public:maven-gradleplugins
    Default: public:maven-central
  GitHubConnectionArn:
    Description: Enter GitHub connection ARN
    Type: String
    Default: arn:aws:codestar-connections:eu-north-1:166601305423:connection/8cf74261-d8ef-4cd4-b062-9247dee0e76b
  GitHubRepository:
    Description: Enter GitHub repository name
    Type: String
    Default: awscourse
  GitHubBranch:
    Description: Enter repository branch name
    Type: String
    AllowedValues:
      - master
      - main
    Default: master
  GitHubUser:
    Description: Enter GitHub user name
    Type: String
    Default: Competency-Development-Workshop

Resources:
  CodeArtifactDomain:
    Type: AWS::CodeArtifact::Domain
    Properties:
      DomainName: code-artifact-domain
  CodeArtifactUpstreamRepository:
    Type: AWS::CodeArtifact::Repository
    Properties:
      RepositoryName: CodeArtifactUpstreamRepository
      DomainName: !GetAtt CodeArtifactDomain.Name
      ExternalConnections:
        - !Ref CodeArtifactCentralStore
  CodeArtifactRepository:
    Type: AWS::CodeArtifact::Repository
    Properties:
      RepositoryName: CodeArtifactRepository
      DomainName: !GetAtt CodeArtifactDomain.Name
      Upstreams:
        - !GetAtt CodeArtifactUpstreamRepository.Name

  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete

  CodeBuildRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Effect: Allow
              Principal:
                Service: 
                  - codebuild.amazonaws.com
              Action: 
                - sts:AssumeRole
        Path: /
        Policies:
          - PolicyName: CodeBuildLogsPolicy
            PolicyDocument:
              Statement:
                  - Effect: Allow
                    Action:
                        - logs:CreateLogGroup
                        - logs:CreateLogStream
                        - logs:PutLogEvents
                        - ecr:GetAuthorizationToken
                        - ssm:GetParameters
                    Resource: "*"
          - PolicyName: CodeBuildS3Policy
            PolicyDocument:
              Statement:
                  - Effect: Allow
                    Action:
                        - s3:GetObject
                        - s3:PutObject
                        - s3:GetObjectVersion
                    Resource: !Sub arn:aws:s3:::${S3Bucket}/*
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec.yml
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:6.0
        Type: LINUX_CONTAINER
      Name: !Ref AWS::StackName
      ServiceRole: !Ref CodeBuildRole

  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - !Join ["", [codedeploy., !Ref AWS::Region, .amazonaws.com]]
                # - !Sub codedeploy.${AWS::Region}.amazonaws.com
            Action: 
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: CodeDeployPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ec2:Describe*
                  - autoscaling:CompleteLifecycleAction
                  - autoscaling:DeleteLifecycleHook
                  - autoscaling:DescribeLifecycleHooks
                  - autoscaling:DescribeAutoScalingGroups
                  - autoscaling:PutLifecycleHook
                  - autoscaling:RecordLifecycleActionHeartbeat
                Resource: "*"
  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
  OrderServiceCodeDeployGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: "order"
      Ec2TagFilters:
        - Key: Name
          Value: !Select [0, !Split [",", !Ref TagNameValue]]
          Type: KEY_AND_VALUE
      ServiceRoleArn: !GetAtt CodeDeployRole.Arn
  BillingServiceCodeDeployGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: "billing"
      Ec2TagFilters:
        - Key: Name
          Value: !Select [1, !Split [",", !Ref TagNameValue]]
          Type: KEY_AND_VALUE
      ServiceRoleArn: !GetAtt CodeDeployRole.Arn

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - codepipeline.amazonaws.com
            Action: 
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub arn:aws:s3:::${S3Bucket}/*
                  - !Sub arn:aws:s3:::${S3Bucket}
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                  - iam:PassRole
                Resource: "*"
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource:
                  - !Ref GitHubConnectionArn  # This ARN can be replaced with Connection resource
              - Effect: Allow
                Action:
                  - codedeploy:CreateDeployment
                  - codedeploy:CreateDeploymentGroup
                  - codedeploy:GetApplication
                  - codedeploy:GetApplicationRevision
                  - codedeploy:GetDeployment
                  - codedeploy:GetDeploymentConfig
                  - codedeploy:RegisterApplicationRevision
                Resource: "*"
  CodePipelineForApplication:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref S3Bucket
      Stages:
        - Name: Pull
          Actions:
            - Name: PullGithubChanges
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              Configuration:
                ConnectionArn: !Ref GitHubConnectionArn # This ARN can be replaced with Connection resource
                BranchName: !Ref GitHubBranch
                FullRepositoryId: !Sub ${GitHubUser}/${GitHubRepository}
              OutputArtifacts:
                - Name: ApplicationArtifact
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildApplication
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: ApplicationArtifact
              OutputArtifacts:
                - Name: ApplicationBuildArtifact
              RunOrder: 1
        - Name: DeployOrderService
          Actions:
            - Name: DeployApplication
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CodeDeploy
              Configuration:
                ApplicationName: !Ref CodeDeployApplication
                DeploymentGroupName: !Ref OrderServiceCodeDeployGroup
              InputArtifacts:
                - Name: ApplicationBuildArtifact
              RunOrder: 1
        - Name: DeployBillingService
          Actions:
            - Name: DeployApplication
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CodeDeploy
              Configuration:
                ApplicationName: !Ref CodeDeployApplication
                DeploymentGroupName: !Ref BillingServiceCodeDeployGroup
              InputArtifacts:
                - Name: ApplicationBuildArtifact
              RunOrder: 2

Outputs:
  PipelineForApplicationUrl:
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${CodePipelineForApplication}