AWSTemplateFormatVersion: 2010-09-09
Description: Root template for other stacks. All underlying stacks should be uploaded to the S3 bucket.

Parameters:
  EnvironmentType:
    Description: Choose which environment should be used
    Type: String
    AllowedValues:
      - dev
      - test
    Default: dev
  S3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-.]*[0-9a-zA-Z])*$
    ConstraintDescription: Bucket name can include numbers, lowercase letters, uppercase letters, periods (.), and hyphens (-). It cannot start or end with a hyphen (-).
    Description: S3 bucket name for the Nested Stacks. S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Type: String
    Default: awscourse-cf-templates.s3.eu-north-1
  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.192.0.0/16
  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.192.10.0/24
  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 10.192.11.0/24
  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.192.20.0/24
  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.192.21.0/24

# EC2 parameters
  AvailabilityZone:
    Description: Choose AZ, which should be used for EC2 creation
    Type: AWS::EC2::AvailabilityZone::Name
    Default: eu-north-1a
  # AmiID:
  #   Description: Enter AMI id
  #   Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
  #   Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64
  KeyPairName:
    Description: Choose key-pair name for EC2
    Type: AWS::EC2::KeyPair::KeyName
    Default: Pair
  Ec2TagName:
    Description: Enter tag name for EC2
    Type: String
    Default: EC2CloudFormation
  RdsTagValue:
    Description: Enter tag name value for RDS
    Type: String
    Default: RDSCloudFormation

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.amazonaws.com/cf-vpc.yaml
      TimeoutInMinutes: 20
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR

  Ec2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.amazonaws.com/cf-ec2.yaml
      TimeoutInMinutes: 20
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        AvailabilityZone: !Ref AvailabilityZone
        #AmiID: !Ref AmiID
        KeyPairName: !Ref KeyPairName
        TagNameValue: !Ref Ec2TagName
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        SubnetId: !GetAtt VpcStack.Outputs.PublicSubnet1

  RdsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${S3BucketName}.amazonaws.com/cf-rds.yaml
      TimeoutInMinutes: 20
      Parameters:
        EnvironmentType: !Ref EnvironmentType
        TagValue: !Ref RdsTagValue
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        SubnetId1: !GetAtt VpcStack.Outputs.PublicSubnet1
        SubnetId2: !GetAtt VpcStack.Outputs.PublicSubnet2

Outputs:
  WebsiteURL:
    Value: !GetAtt Ec2Stack.Outputs.WebsiteURL