Parameters:
  EnvironmentType:
    Description: Choose which environment should be used
    Type: String
    AllowedValues:
      - dev
      - test
    Default: dev
  TagValue:
    Description: Tag Name value for RDS
    Type: "String"
  DBName:
    Description: PostgeSQL database name
    Type: "String"
    Default: "billingservice"
  DBUsername:
    Description: PostgreSQL username
    Type: "String"
    Default: "testuser"
  DBPassword:
    Description: PostgreSQL password
    Type: "String"
    Default: "secret123"
  VpcId:
    Description: The VPC ID
    Type: AWS::EC2::VPC::Id
  SubnetId1:
    Description: The ID of subnet with first AZ
    Type: AWS::EC2::Subnet::Id
  SubnetId2:
    Description: The ID of subnet with second AZ
    Type: AWS::EC2::Subnet::Id

Resources:
  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: "rds-subnet-group"
      DBSubnetGroupDescription: "RDS subnet group"
      SubnetIds:
        - !Ref SubnetId1
        - !Ref SubnetId2
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ["-", [rds-ec2-sg, !Ref EnvironmentType]]
      GroupDescription: "Allow RDS traffic"
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          CidrIp: "0.0.0.0/0"
          FromPort: 5432
          ToPort: 5432

  Instance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName: !Ref SubnetGroup
      VPCSecurityGroups:
        - !Ref InstanceSecurityGroup
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "5"
      Engine: postgres
      EngineVersion: "15.2"
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      Tags:
        - Key: Name
          Value: !Ref TagValue
    UpdateReplacePolicy: Snapshot
    DeletionPolicy: Delete
  
  DatabaseURLParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${DBName}_${EnvironmentType}/spring.datasource.url
      Type: String
      Value: !Sub jdbc:postgresql://${Instance.Endpoint.Address}:${Instance.Endpoint.Port}/${DBName}

  DatabaseUsernameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${DBName}_${EnvironmentType}/spring.datasource.username
      Type: String
      Value: !Ref DBUsername

  DatabasePasswordParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub /config/${DBName}_${EnvironmentType}/spring.datasource.password
      Type: String
      Value: !Ref DBPassword