Parameters:
  Tag:
    Description: Tag for RDS
    Type: "String"
  DBInstanceIdentifier:
    Description: RDS instance name
    Type: String
    Default: "database-x"
  DBName:
    Description: PostgeSQL database name
    Type: "String"
    Default: "postgres"
  DBUsername:
    Description: PostgreSQL username
    Type: "String"
    Default: "postgres"
  DBPassword:
    Description: PostgreSQL password
    Type: "String"
    Default: "postgres"
  VpcId:
    Description: The VPC ID
    Type: AWS::EC2::VPC::Id
  SubnetId1:
    Description: The ID of subnet with first AZ
    Type: AWS::EC2::Subnet::Id
  SubnetId2:
    Description: The ID of subnet with second AZ
    Type: AWS::EC2::Subnet::Id

Resources:

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VpcId

  SubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: "rds-subnet-group"
      DBSubnetGroupDescription: "RDS subnet group"
      SubnetIds:
        - !Ref SubnetId1
        - !Ref SubnetId2

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "rds-ec2-sg"
      GroupDescription: "Allow RDS traffic"
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: "0.0.0.0/0"

  InstanceSecurityGroupIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: InstanceSecurityGroup
    Properties:
      GroupId: !Ref InstanceSecurityGroup
      IpProtocol: "tcp"
      FromPort: 5432
      ToPort: 5432
      SourceSecurityGroupId: !Ref InstanceSecurityGroup

  Instance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBSubnetGroupName: !Ref SubnetGroup
      VPCSecurityGroups:
        - !Ref InstanceSecurityGroup
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "5"
      Engine: postgres
      EngineVersion: "15.2"
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      Tags:
        - Key: Name
          Value: !Ref Tag
    UpdateReplacePolicy: Snapshot
    DeletionPolicy: Delete
  
  DatabaseURLParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Join ["-", [!Ref Tag, RdsUrl]] # add environment prefix to the value name
      Type: String
      Value: !Join [":", [!GetAtt Instance.Endpoint.Address, !GetAtt Instance.Endpoint.Port]]