AWSTemplateFormatVersion: '2010-09-09'
Description: This stack creates a Standard Queue
Parameters:
  MaximumMessageSize:
    Type: Number
    Description: "The limit of how many bytes that a message can contain before Amazon SQS rejects it. Default 256KiB"
    Default: '262144'
  MessageRetentionPeriod:
    Description: "The number of seconds that Amazon SQS retains a message."
    Type: Number
    Default: '345600'
  ReceiveMessageWaitTimeSeconds:
    Description: "Specifies the duration, in seconds, that the ReceiveMessage action call waits 
    until a message is in the queue in order to include it in the response. Used for long polling"
    Type: Number
    Default: '0'
  VisibilityTimeout:
    Description: "The length of time during which a message will be unavailable after a message is delivered from the queue. 
    This should be longer than the time it would take to process and delete a message"
    Type: Number
    Default: '5'
Resources:
  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      MaximumMessageSize:
        Ref: MaximumMessageSize
      MessageRetentionPeriod:
        Ref: MessageRetentionPeriod
      ReceiveMessageWaitTimeSeconds:
        Ref: ReceiveMessageWaitTimeSeconds
      VisibilityTimeout:
        Ref: VisibilityTimeout
Outputs:
  QueueURL:
    Description: URL of the created SQS
    Value:
      Ref: SQSQueue
  QueueARN:
    Description: ARN of the created SQS
    Value:
      Fn::GetAtt:
        - SQSQueue
        - Arn
  QueueName:
    Description: Name of the created SQS
    Value:
      Fn::GetAtt:
        - SQSQueue
        - QueueName