cloud:
  aws:
    region:
      static: eu-central-1
    credentials:
      instanceProfile: true

s3:
  bucket:
    name: dzmitry-static-billing-service

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
